version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./PDF:/app/PDF

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend 